[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
confidential_perps = "4SRWjriSqi6h3ec7peAFkHFdELpHw84gKSXKs14Q9ErG"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[hooks]

[test.validator]
startup_wait = 10000
